add_newline = false
[line_break]
disabled = true
[hostname]
ssh_only = false
[username]
show_always = true
[battery]
full_symbol = "🔋"
charging_symbol = "🔌"
discharging_symbol = "⚡"
[[battery.display]]
threshold = 75
style = "green"
[[battery.display]]
threshold = 50
style = "yellow"
[[battery.display]]
threshold = 25
style = "red"
[[battery.display]]
threshold = 10
style = "bold red"
